//environment = "dev"
s3_bucket = "jenkins-instance-beck"
s3_folder_project = "jenkins"
s3_folder_region = "us-east-1"
s3_folder_type = "hw2"
s3_tfstate_file = "infrastructure.tfstate"
# TF_LOG = ${var.DEBUG}
TF_LOG_PATH=
TF_LOG = "TRACE"